version: '3'

services:
  mongodb:
    container_name: mongodb_container
    image: mongo:6.0.13
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: task_tracker_db